import { useEffect } from 'react'
import QueryBar from './QueryBar'

// Full-screen animated schematic of the RAG pipeline, opened by clicking the
// dock readout. The SVG scene shows the query moving through six stations;
// a row of step cards below narrates each stage in plain language, lighting
// up in sync with the animation. Stage state is shared with the dock readout
// so this tracks the live query, not a canned loop.

const CX = [95, 289, 483, 677, 871, 1065]
const BASE_Y = 118

const STATIONS = [
  { label: 'OPERATOR QUERY', sub: 'HMI CONSOLE' },
  { label: 'EMBED', sub: '768-DIM VECTOR' },
  { label: 'VECTOR SEARCH', sub: 'CHROMADB · LOCAL' },
  { label: 'TOP-2 PROCEDURES', sub: 'WHOLE SOP CHUNKS' },
  { label: 'LLM SYNTHESIS', sub: 'LLAMA 3.2 · OLLAMA' },
  { label: 'CITED RESPONSE', sub: 'VERBATIM + SOURCES' },
]

// One card per dock stage (0-4), shown under the scene. The active one
// glows amber; completed ones edge green.
const STEPS = [
  {
    num: '01',
    title: 'QUERY DISPATCH',
    body: 'The operator’s question — typed, or generated by clicking a live alarm — posts to the FastAPI RAG service on the plant network. There is no cloud round-trip at any point.',
  },
  {
    num: '02',
    title: 'EMBED + SEMANTIC SEARCH',
    body: 'nomic-embed-text converts the question into a 768-dimension vector. ChromaDB compares it against every indexed SOP chunk by cosine similarity — meaning, not keywords.',
  },
  {
    num: '03',
    title: 'TOP-2 RETRIEVAL',
    body: 'The two closest chunks are retrieved whole. One chunk = one complete procedure, so steps from different alarms are never blended together.',
  },
  {
    num: '04',
    title: 'GUARDED SYNTHESIS',
    body: 'Llama 3.2 runs locally via Ollama under a strict guardrail: answer only from the retrieved text, and only if equipment AND condition both match — otherwise refuse.',
  },
  {
    num: '05',
    title: 'DELIVERY + AUDIT',
    body: 'The verbatim steps return with source files and match scores, and the full exchange is appended to the audit log — a compliance trail of what the system told operators.',
  },
]

const CAPTIONS = [
  '1 · QUERY DISPATCHED',
  '2 · SEMANTIC SEARCH OVER SOP LIBRARY',
  '3 · TOP-2 PROCEDURES RETRIEVED',
  '4 · SYNTHESIZING — 100% LOCAL',
  '5 · CITED PROCEDURE DELIVERED',
]

// Fixed pseudo-random scatter for the vector field. Two of them ("hits")
// light up green once the search stage has run.
const FIELD_DOTS = [
  [-24, -14], [-15, 8], [-6, -18], [-1, 3], [8, -10], [17, 12],
  [24, -16], [-27, 12], [12, 1], [22, 4], [-10, -5], [3, 15], [-20, -2], [27, -4],
]
const HIT_DOTS = [[-6, 6], [15, -8]]

// The three SOP documents feeding the vector store at index time.
const LIB_DOCS = [-38, 0, 38]

function stationState(i, activeStation, running, settled) {
  if (!running) return 'idle'
  if (settled) return 'done'
  if (i < activeStation) return 'done'
  if (i === activeStation) return 'active'
  return 'idle'
}

export default function PipelineDetail({ open, onClose, busy, stage, settled, exchange, onSubmit }) {
  useEffect(() => {
    if (!open) return
    function onKey(e) {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    document.body.style.overflow = 'hidden'
    return () => {
      window.removeEventListener('keydown', onKey)
      document.body.style.overflow = ''
    }
  }, [open, onClose])

  if (!open) return null

  const running = busy || settled
  // Map the 5 dock stages onto 6 stations: the query leaves station 0
  // immediately, so stage 0 animates the embed station, and so on down the line.
  const activeStation = settled ? 5 : busy ? Math.min(stage + 1, 5) : -1

  const question = exchange?.question
  const answerText = exchange?.status === 'done' ? exchange.result?.answer : null
  const sources = exchange?.status === 'done' ? exchange.result?.sources : null
  const caption = running
    ? (settled ? CAPTIONS[4] : CAPTIONS[Math.min(stage, 3)])
    : 'IDLE — RUN A QUERY TO SEE THE PIPELINE LIVE'

  const states = STATIONS.map((_, i) => stationState(i, activeStation, running, settled))
  const searchDone = states[2] === 'done'
  const chunksIn = states[3] === 'done' || states[3] === 'active'

  // Once the response lands we know the real similarity scores — surface
  // them right on the vector-search station.
  const scoreSub = settled && sources?.length
    ? `MATCH ${sources.slice(0, 2).map((s) => (s.score ?? 0).toFixed(2)).join(' · ')}`
    : STATIONS[2].sub

  return (
    <div className="pd-overlay" onClick={onClose}>
      <div className="pd-modal" role="dialog" aria-modal="true" aria-label="RAG pipeline detail" onClick={(e) => e.stopPropagation()}>
        <header className="pd-header">
          <div>
            <h2>BEHIND THE SCENES — AI RAG PIPELINE</h2>
            <span className="pd-subtitle">EVERY STEP RUNS ON THIS MACHINE · NO DATA LEAVES THE SITE</span>
          </div>
          <button type="button" className="pd-close" onClick={onClose} aria-label="Close">✕</button>
        </header>

        <div className="pd-scene">
          <svg viewBox="0 0 1160 212" preserveAspectRatio="xMidYMid meet">
            {/* ---- SOP library feeding the vector store (index time) ---- */}
            <g className="pd-lib" transform={`translate(${CX[2]},14)`}>
              <text className="pd-lib-label" y="-2" textAnchor="middle">
                SOP LIBRARY — 3 DOCS · 10 PROCEDURES · INDEXED AT STARTUP
              </text>
              {LIB_DOCS.map((dx) => (
                <g key={dx} transform={`translate(${dx},10)`}>
                  <rect x="-8" y="0" width="16" height="20" rx="2" />
                  <path d="M-4,5 h8 M-4,10 h8 M-4,15 h5" />
                  <path className="pd-lib-feed" d={`M0,22 L${-dx * 0.6},${BASE_Y - 52}`} />
                </g>
              ))}
            </g>

            {/* ---- connectors ---- */}
            {[1, 2, 3, 4, 5].map((i) => {
              const x1 = CX[i - 1] + 52
              const x2 = CX[i] - 52
              const flowing = running && !settled && i === activeStation
              const passed = settled || (running && i < activeStation)
              return (
                <g key={i}>
                  <line
                    className={`pd-seg ${flowing ? 'flowing' : passed ? 'passed' : ''}`}
                    x1={x1} y1={BASE_Y} x2={x2} y2={BASE_Y}
                  />
                  <polygon
                    className={`pd-seg-head ${flowing ? 'flowing' : passed ? 'passed' : ''}`}
                    points={`${x2 + 8},${BASE_Y} ${x2},${BASE_Y - 4.5} ${x2},${BASE_Y + 4.5}`}
                  />
                  {flowing && [0, 0.45].map((delay) => (
                    <circle key={delay} className="pd-packet" r="3.4">
                      <animateMotion
                        path={`M ${x1},${BASE_Y} L ${x2},${BASE_Y}`}
                        dur="0.9s"
                        begin={`${delay}s`}
                        repeatCount="indefinite"
                      />
                    </circle>
                  ))}
                </g>
              )
            })}

            {/* ---- station 0: operator HMI ---- */}
            <g transform={`translate(${CX[0]},${BASE_Y})`} className={`pd-station pd-station-${states[0]}`}>
              <rect x="-26" y="-26" width="52" height="36" rx="4" />
              <path d="M0,10 v7 M-12,17 h24" />
              <path className="pd-alarm-tri" d="M0,-21 L9,-4 L-9,-4 Z" />
              <path d="M0,-16 v6 M0,-7.5 v0.5" />
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[0].label}</text>
              <text className="pd-st-sub" y="64" textAnchor="middle">{STATIONS[0].sub}</text>
            </g>

            {/* ---- station 1: embedding — text becomes a vector grid ---- */}
            <g transform={`translate(${CX[1]},${BASE_Y})`} className={`pd-station pd-station-${states[1]}`}>
              <path d="M-26,-18 h-7 v36 h7" />
              <path d="M26,-18 h7 v36 h-7" />
              {[-14, -4, 6].map((gx, col) =>
                [-14, -4, 6].map((gy, row) => (
                  <rect
                    key={`${col}-${row}`}
                    className={`pd-cell ${states[1] === 'active' ? 'pd-cell-anim' : ''}`}
                    style={{ animationDelay: `${(col * 3 + row) * 0.09}s` }}
                    x={gx + 4} y={gy} width="7" height="7" rx="1.5"
                  />
                ))
              )}
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[1].label}</text>
              <text className="pd-st-sub" y="64" textAnchor="middle">{STATIONS[1].sub}</text>
            </g>

            {/* ---- station 2: vector field with radar sweep ---- */}
            <g transform={`translate(${CX[2]},${BASE_Y})`} className={`pd-station pd-station-${states[2]}`}>
              <rect x="-38" y="-28" width="76" height="56" rx="10" />
              {FIELD_DOTS.map(([dx, dy]) => (
                <circle key={`${dx},${dy}`} className="pd-fdot" cx={dx} cy={dy} r="2.2" />
              ))}
              {HIT_DOTS.map(([dx, dy]) => (
                <circle key={`${dx},${dy}`} className={`pd-fdot pd-fdot-hit ${searchDone ? 'lit' : ''}`} cx={dx} cy={dy} r="3.2" />
              ))}
              {states[2] === 'active' && (
                <>
                  <circle className="pd-ring" cx="0" cy="0" r="10" />
                  <circle className="pd-ring pd-ring-late" cx="0" cy="0" r="10" />
                </>
              )}
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[2].label}</text>
              <text className={`pd-st-sub ${scoreSub !== STATIONS[2].sub ? 'pd-st-sub-score' : ''}`} y="64" textAnchor="middle">{scoreSub}</text>
            </g>

            {/* ---- station 3: the two retrieved procedure chunks ---- */}
            <g transform={`translate(${CX[3]},${BASE_Y})`} className={`pd-station pd-station-${states[3]}`}>
              <g className={`pd-doc pd-doc-back ${chunksIn ? 'in' : ''}`}>
                <rect x="-8" y="-14" width="26" height="34" rx="3" />
                <path d="M-3,-6 h16 M-3,2 h16 M-3,10 h10" />
              </g>
              <g className={`pd-doc ${chunksIn ? 'in' : ''}`}>
                <rect x="-18" y="-20" width="26" height="34" rx="3" />
                <path d="M-13,-12 h16 M-13,-4 h16 M-13,4 h10" />
              </g>
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[3].label}</text>
              <text className="pd-st-sub" y="64" textAnchor="middle">{STATIONS[3].sub}</text>
            </g>

            {/* ---- station 4: LLM chip, guardrail shield attached ---- */}
            <g transform={`translate(${CX[4]},${BASE_Y})`} className={`pd-station pd-station-${states[4]}`}>
              {states[4] === 'active' && (
                <>
                  <circle className="pd-ring" cx="0" cy="0" r="14" />
                  <circle className="pd-ring pd-ring-late" cx="0" cy="0" r="14" />
                </>
              )}
              <rect x="-18" y="-18" width="36" height="36" rx="6" />
              <rect x="-8" y="-8" width="16" height="16" rx="2" />
              <path d="M-6,-18 v-7 M6,-18 v-7 M-6,18 v7 M6,18 v7 M-18,-6 h-7 M-18,6 h-7 M18,-6 h7 M18,6 h7" />
              <g className="pd-shield" transform="translate(34,-32)">
                <path d="M0,-9 L9,-5 V2 C9,8 0,12 0,12 C0,12 -9,8 -9,2 V-5 Z" />
                <path d="M-3.5,0.5 l2.5,2.5 l5,-5.5" />
              </g>
              <text className="pd-shield-label" x="34" y="-46" textAnchor="middle">GUARDRAIL</text>
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[4].label}</text>
              <text className="pd-st-sub" y="64" textAnchor="middle">{STATIONS[4].sub}</text>
            </g>

            {/* ---- station 5: cited response ---- */}
            <g transform={`translate(${CX[5]},${BASE_Y})`} className={`pd-station pd-station-${states[5]}`}>
              <path d="M-24,-20 h48 a8,8 0 0 1 8,8 v16 a8,8 0 0 1 -8,8 h-30 l-10,10 v-10 h-8 a8,8 0 0 1 -8,-8 v-16 a8,8 0 0 1 8,-8 Z" />
              <path className={`pd-check ${settled || states[5] === 'done' ? 'drawn' : ''}`} d="M-11,-2 l7,7 l15,-15" />
              <text className="pd-st-label" y="48" textAnchor="middle">{STATIONS[5].label}</text>
              <text className="pd-st-sub" y="64" textAnchor="middle">{STATIONS[5].sub}</text>
            </g>
          </svg>
        </div>

        {/* Live query in / answer out, one line each. */}
        <div className="pd-io">
          <span className="pd-io-q">&gt; {question ?? 'AWAITING QUERY'}</span>
          <span className="pd-io-a">
            {busy && !settled
              ? <span className="blink">SYNTHESIZING…</span>
              : answerText
                ? answerText.replace(/\s+/g, ' ')
                : '—'}
          </span>
        </div>

        {/* Fire a query without leaving the detail view — the scene above
            animates it live. */}
        <div className="pd-query-bar">
          <QueryBar onSubmit={onSubmit} busy={busy} />
        </div>

        {/* Step-by-step narration, synced to the scene above. */}
        <div className="pd-steps">
          {STEPS.map((step, i) => {
            const state = !running ? '' : settled || stage > i ? 'pd-step-done' : stage === i ? 'pd-step-active' : ''
            return (
              <div key={step.num} className={`pd-step ${state}`}>
                <div className="pd-step-head">
                  <span className="pd-step-num">{step.num}</span>
                  <h3>{step.title}</h3>
                </div>
                <p>{step.body}</p>
              </div>
            )
          })}
        </div>

        <footer className={`pd-caption ${settled ? 'pd-caption-done' : ''}`}>
          {caption}
        </footer>
      </div>
    </div>
  )
}
